# Generated by Django 3.2.13 on 2022-05-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('password', models.SlugField(max_length=250, unique=True)),
                ('cpassword', models.TextField(max_length=250, unique=True)),
            ],
        ),
    ]
