# Generated by Django 3.2.13 on 2022-05-31 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='cpassword',
        ),
    ]
