# Generated by Django 3.2.13 on 2022-06-02 08:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_remove_user_details_cpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
